### ISSUE TITLE
Changing the audio device in the audio player panel has no effect

### ISSUE THREAD

**Issue by jdperos** [KillzXGaming/Switch-Toolbox#187]
AudioPlayer.audioDevice_SelectedIndexChanged() is an empty function

**Comment by KillzXGaming** [comment]
This should be fixed now. https://github.com/KillzXGaming/Switch-Toolbox/commit/ecf8dae084e5893b29eb27305ffa9e2fbc8ec86e

**Comment by jdperos** [comment]
Issue persists, changing the audio device does not change the output from my computer.

A breakpoint in AudioPlay.audioDevice_SelectedIndexChanged() is never hit. There is a breakpoint that is hit in AudioPlayerPanel.audioDevice_SelectedIndexChanged(), which is hit appropriately when another audio device is selected, but it has no effect on the output from my computer.
